### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: init.js

### ISSUE THREAD

**Issue by mc-jiang** [wikkiewikkie/flask-googlecharts#2]
I installed the module and followed the simple example in source code, but am getting error says jinja2 unable to find template. here's the traceback:
`Traceback (most recent call last):
  File "run.py", line 29, in <module>
    charts = GoogleCharts(app)
  File "/Users/sara/Documents/Github/PerformanceVision/pv_venv/lib/python2.7/site-packages/flask_googlecharts/__init__.py", line 218, in __init__
    self.init_app(self.app)
  File "/Users/sara/Documents/Github/PerformanceVision/pv_venv/lib/python2.7/site-packages/flask_googlecharts/__init__.py", line 235, in init_app
    self.templates['init'] = self.template_env.get_template("init.js")
  File "/Users/sara/Documents/Github/PerformanceVision/pv_venv/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/sara/Documents/Github/PerformanceVision/pv_venv/lib/python2.7/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/Users/sara/Documents/Github/PerformanceVision/pv_venv/lib/python2.7/site-packages/jinja2/loaders.py", line 235, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: init.js`

**Comment by idiotsavant** [comment]
I have the same issue. It looks like the **templates** and **static** folders are missing after installing with pip. Tried easy_install too but that made no difference.

**Comment by ryan413** [comment]
@idiotsavant got a link?

**Comment by mc-jiang** [comment]
@idiotsavant where do you put those files?

**Comment by ryan413** [comment]
@idiotsavant link to release 0.0.3

**Comment by idiotsavant** [comment]
It's on this github repository, under Code > Releases > 0.0.3

https://github.com/wikkiewikkie/flask-googlecharts/releases/tag/v0.0.3

**Comment by lexandro70** [comment]
@idiotsavant Thanks!

**Comment by wikkiewikkie** [comment]
resolved with PR #4
